name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          VITE_API_URL: "https://api.meuplantel.com"
          VITE_HCAPTCHA_SITEKEY: "bbc0cbf8-ae7a-40c2-a870-959019e6a484"
          VITE_TURNSTILE_SITEKEY: "0x4AAAAAACXtMXHoznt_Lt9Z"

      - name: 📂 Sync files meuplantel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 192.185.215.244
          username: app2@meuplantel.com
          password: ${{ secrets.FTP_APP2 }}
          server-dir: ./app2.meuplantel.com/
          local-dir: ./dist/